---
title: "HW 01"
author: "Shakir Ahmed"
format: html
date: 2023-09-08 (YYYY-MM-DD)
toc: true
---

##Setup
```{r include=FALSE, warning = FALSE, message=FALSE}
# Install & load packages
#Accidents dataset is within dsbox package

install.packages("pacman")
pacman::p_load("tidyverse")
pacman::p_load_gh("rstudio-education/dsbox")


theme_set(theme_minimal(base_size = 11))

### setting theme for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 14))

# setting width of code output
options(width = 65)

# setting figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7,        # 7" width
  fig.asp = 0.618,      # the golden ratio
  fig.retina = 4,       # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 500             # higher dpi, sharper image
)

```

## 1 - Road traffic accidents in Edinburgh


```{r warning = FALSE, message=FALSE}

# Create a vector of weekdays and weekends
day_type_vector <- c(
  Monday = "Weekday", Tuesday = "Weekday", Wednesday = "Weekday", Thursday = "Weekday", Friday = "Weekday",
  Saturday = "Weekend", Sunday = "Weekend"
)

# Function to identify the day type
type <- function(day_of_week) 
{
  return(ifelse(day_of_week %in% names(day_type_vector), day_type_vector[day_of_week], "NA"))
}


# Process the data and add a new column for day_type
accidents$day_type <- sapply(accidents$day_of_week, type)

# Create a ggplot visualization
ggplot(data = accidents, aes(x = time, fill = severity)) +
  geom_density(alpha = 0.3) +
  facet_wrap(~ day_type, ncol = 1) +
  labs(
    x        = "Time of the day",
    y        = "Density",
    title    = "Number of accidents throughout the day",
    subtitle = "By day of week and severity",
  )

```

## 2 - NYC marathon winners

```{r label-me-2}

```

## 3 - US counties

## 4 - Rental apartments in SF

## 5 - Napoleon's march.
